[general]
sta = "ILAB"
net= "II"
loc= "21"

[oids]
# OIDs for EMC-1 bridge
emcoids = [
    { oid = "1.3.6.1.4.1.33333.1.1.0", chancode = "", label = "EMC-1 Serial Number", units = "", type = "string", scaling = 1.0 },
    { oid = "1.3.6.1.4.1.33333.1.2.0", chancode = "", label = "EMC-1 FW Version", units = "", type = "string", scaling = 1.0 },
    { oid = "1.3.6.1.4.1.33333.1.3.0", chancode = "", label = "EMC-1 Build Number", units = "", type = "string", scaling = 1.0 },
]

# Array of model group OIDs
# first model group: TS-MPPT
devicegroups = [
    {
        groupoid = "1.3.6.1.4.1.33333.2.1.0",
        modelgroup = "TS-MPPT", 
        modellist = ["TS-MPPT-45", "TS-MPPT-60"],
        static = [
            { oid = "1.3.6.1.4.1.33333.2.1.0", chancode = "", label = "Controller", units = "", type = "string", scaling = 1.0, register = "", regtype = "text" },
            { oid = "1.3.6.1.4.1.33333.2.2.0", chancode = "", label = "Serial number", units = "", type = "string", scaling = 1.0, register = "", regtype = "text" },
            { oid = "1.3.6.1.4.1.33333.2.3.0", chancode = "", label = "Hardware version (vHW1.HW2.FW)", units = "", type = "string", scaling = 1.0, register = "", regtype = "text" },
            { oid = "1.3.6.1.4.1.33333.2.61.0", chancode = "", label = "uP A software version", units = "", type = "string", scaling = 1.0, register = "", regtype = "text" },
            { oid = "1.3.6.1.4.1.33333.2.62.0", chancode = "", label = "uP B software version", units = "", type = "string", scaling = 1.0, register = "", regtype = "text" },
        ], 
        status = [
            { oid = "1.3.6.1.4.1.33333.2.60.0", chancode = "", label = "DIP Switches", units = "", type = "bitreverse", scaling = 8 },
            { oid = "1.3.6.1.4.1.33333.2.59.0", chancode = "", label = "Runtime", units = "hours", type = "number", scaling = 1 },
            { oid = "1.3.6.1.4.1.33333.2.46.0", chancode = "", label = "Charge State", units = "", type = "map", values = [
                    "start",
                    "nightCheck",
                    "disconnect",
                    "night",
                    "fault",
                    "mppt",
                    "absorption",
                    "float",
                    "equalize",
                    "slave",
                ] },
        ], 
        measurements = [
            { oid = "1.3.6.1.4.1.33333.2.49.0", chancode = "", label = "Heatsink temperature", units = "deg C", type = "number", scaling = 1.0 }, 
            { oid = "1.3.6.1.4.1.33333.2.48.0", chancode = "", label = "Battery temperature", units = "deg C", type = "number", scaling = 1.0 },
            { oid = "1.3.6.1.4.1.33333.2.40.0", chancode = "", label = "Min battery voltage", units = "volts", type = "number", scaling = 0.005493164 },
            { oid = "1.3.6.1.4.1.33333.2.41.0", chancode = "", label = "Max battery voltage", units = "volts", type = "number", scaling = 0.005493164 },
            { oid = "1.3.6.1.4.1.33333.2.33.0", chancode = "", label = "Array power max", units = "watts", type = "number", scaling = 0.109863281 },
            { oid = "1.3.6.1.4.1.33333.2.30.0", chancode = "", label = "Charge voltage", units = "volts", type = "number", scaling = 0.005493164 },
            { oid = "1.3.6.1.4.1.33333.2.43.0", chancode = "", label = "Charge current", units = "amps", type = "number", scaling = 0.002441406 },
            { oid = "1.3.6.1.4.1.33333.2.38.0", chancode = "", label = "Battery voltage", units = "volts", type = "number", scaling = 0.005493164 },
            { oid = "1.3.6.1.4.1.33333.2.39.0", chancode = "", label = "Battery sense voltage", units = "volts", type = "number", scaling = 0.005493164 },
            { oid = "1.3.6.1.4.1.33333.2.45.0", chancode = "", label = "Target voltage", units = "volts", type = "number", scaling = 0.005493164 },
        ], 
        alarms = [
            { oid = "1.3.6.1.4.1.33333.2.57.0",  chancode = "", label = "Alarms (now)", units = "", type = "bitmap", values = [
                    "rtsOpen",
                    "rtsShorted",
                    "rtsDisconnected",
                    "heatsinkTempSensorOpen",
                    "heatsinkTempSensorShorted",
                    "highTemperatureCurrentLimit",
                    "currentLimit",
                    "currentOffset",
                    "batterySense",
                    "batterySenseDisconnected",
                    "uncalibrated",
                    "rtsMiswire",
                    "highVoltageDisconnect",
                    "undefined",
                    "systemMiswire",
                    "mosfetSOpen",
                    "p12VoltageReferenceOff",
                    "highArrayVCurrentLimit",
                    "maxAdcValueReached",
                    "controllerWasReset",
                    "alarm21Undefined",
                    "alarm22Undefined","alarm23Undefined",
                    "alarm24Undefined"
                ] },
            { oid = "1.3.6.1.4.1.33333.2.58.0",  chancode = "", label = "Alarms (today)", units = "", type = "bitmap", values = [
                    "rtsOpen",
                    "rtsShorted",
                    "rtsDisconnected",
                    "heatsinkTempSensorOpen",
                    "heatsinkTempSensorShorted",
                    "highTemperatureCurrentLimit",
                    "currentLimit",
                    "currentOffset",
                    "batterySense",
                    "batterySenseDisconnected",
                    "uncalibrated",
                    "rtsMiswire",
                    "highVoltageDisconnect",
                    "undefined",
                    "systemMiswire",
                    "mosfetSOpen",
                    "p12VoltageReferenceOff",
                    "highArrayVCurrentLimit",
                    "maxAdcValueReached",
                    "controllerWasReset",
                    "alarm21Undefined",
                    "alarm22Undefined","alarm23Undefined",
                    "alarm24Undefined"
                ] },
        ], 
        faults = [
            { oid = "1.3.6.1.4.1.33333.2.55.0",  chancode = "", label = "Faults (now)", units = "", type = "bitmap", values = [
                    "overcurrent",
                    "fetShort",
                    "softwareFault",
                    "batteryHvd",
                    "arrayHvd",
                    "dipSwitchChange",
                    "customSettingsEdit",
                    "rtsShorted",
                    "rtsDisconnected",
                    "eepromRetryLimit",
                    "fault11Undefined",
                    "slaveControlTimeout",
                    "fault13Undefined",
                    "fault14Undefined",
                    "fault15Undefined",
                    "fault16Undefined",
                ] },
            { oid = "1.3.6.1.4.1.33333.2.56.0",  chancode = "", label = "Faults (today)", units = "", type = "bitmap", values = [
                    "overcurrent",
                    "fetShort",
                    "softwareFault",
                    "batteryHvd",
                    "arrayHvd",
                    "dipSwitchChange",
                    "customSettingsEdit",
                    "rtsShorted",
                    "rtsDisconnected",
                    "eepromRetryLimit",
                    "fault11Undefined",
                    "slaveControlTimeout",
                    "fault13Undefined",
                    "fault14Undefined",
                    "fault15Undefined",
                    "fault16Undefined",
            ] },
        ]
    },
    {
        groupoid = "1.3.6.1.4.1.33333.8.1.0",
        modelgroup = "TS-PWM",
        modellist = ["TS-45", "TS-60"],
        static = [
            { oid = "1.3.6.1.4.1.33333.8.1.0", chancode = "", label = "Controller", units = "", type = "string", scaling = 1.0 },
            { oid = "1.3.6.1.4.1.33333.8.2.0", chancode = "", label = "Serial number", units = "", type = "string", scaling = 1.0 },
            { oid = "1.3.6.1.4.1.33333.8.3.0", chancode = "", label = "Hardware version (vHW1.HW2.FW)", units = "", type = "string", scaling = 1.0 },
        ],
        status = [
            { oid = "1.3.6.1.4.1.33333.8.44.0", chancode = "", label = "DIP Switches", units = "", type = "bitreverse", scaling = 8 },
            { oid = "1.3.6.1.4.1.33333.8.41.0", chancode = "", label = "Runtime", units = "hours", type = "number", scaling = 1 },
            { oid = "1.3.6.1.4.1.33333.8.47.0", chancode = "", label = "Load State", units = "", type = "map", values = [
                    "START",
                    "NORMAL",
                    "LVDWarning",
                    "LVD",
                    "FAULT",
                    "DISCONNECT",
                    "LVDWarning-1",
                    "OverrideLVD",
                    "EQUALIZE",
                ] },
        ],
        measurements = [
            { oid = "1.3.6.1.4.1.33333.8.36.0", chancode = "SP1", label = "Heatsink temperature", units = "deg C", type = "number", scaling = 1.0 }, 
            { oid = "1.3.6.1.4.1.33333.8.37.0", chancode = "SP2", label = "Battery temperature", units = "deg C", type = "number", scaling = 1.0 },
            { oid = "1.3.6.1.4.1.33333.8.50.0", chancode = "SP3", label = "Min battery voltage", units = "volts", type = "number", scaling = 0.002950043 },
            { oid = "1.3.6.1.4.1.33333.8.51.0", chancode = "SP4", label = "Max battery voltage", units = "volts", type = "number", scaling = 0.002950043 },
            { oid = "1.3.6.1.4.1.33333.8.32.0", chancode = "SP5", label = "Charge/Load voltage", units = "volts", type = "number", scaling = 0.004246521 },
            { oid = "1.3.6.1.4.1.33333.8.34.0", chancode = "SP7", label = "Load current", units = "amps", type = "number", scaling = 0.009664001 },
            { oid = "1.3.6.1.4.1.33333.8.35.0", chancode = "SP8", label = "Battery voltage", units = "volts", type = "number", scaling = 0.002950043 },
        ],
        alarms = [
            { oid = "1.3.6.1.4.1.33333.8.42.0",  chancode = "", label = "Alarms (now)", units = "", type = "bitmap", values = [
                    "rtsOpen", 
                    "rtsShorted", 
                    "rtsDisconnected", 
                    "heatsinkTempSensorOpen", 
                    "heatsinkTempSensorShorted",
                    "highTemperatureCurrentLimit",
                    "currentLimit",
                    "currentOffset", 
                    "batterySense",
                    "batterySenseDisconnected",
                    "uncalibrated",
                    "rtsMiswire", 
                    "highVoltageDisconnect", 
                    "undefined", 
                    "systemMiswire",
                    "mosfetSOpen", 
                    "p12VoltageReferenceOff", 
                    "highArrayVCurrentLimit", 
                    "maxAdcValueReached", 
                    "controllerWasReset",
                    "alarm21Undefined", 
                    "alarm22Undefined",
                    "alarm23Undefined", 
                    "alarm24Undefined"
                ] },
        ],
        faults = [
            { oid = "1.3.6.1.4.1.33333.8.43.0",  chancode = "", label = "Faults (now)", units = "", type = "bitmap", values = [
                    "externalShort",
                    "overcurrent",
                    "mosfetSShorted",
                    "softwareFault",
                    "highVoltageDisconnect",
                    "tristarHot",
                    "dipSwitchChange",
                    "customSettingsEdit",
                    "reset",
                    "systemMiswire",
                    "rtsShorted",
                    "rtsDisconnected",
                    "fault12Undefined",
                    "fault13Undefined",
                    "fault14Undefined",
                    "fault15Undefined",
                ] },

        ]
    }
]